language: python
python:
  - "2.7"
  - "3.4"
sudo: false
  
# install dependencies
install:
  - "pip install -r requirements/test.txt"

# setup symlink for arc
before_script:
  - "mkdir bin"
  - "ln -s /bin/echo bin/arc"
  - "export PATH=$PATH:bin/"

# run tests
script: make test

after_success:
  coveralls
